object RelatorioEmpregados: TRelatorioEmpregados
  Left = 0
  Top = 0
  Caption = 'Relatorio de Empregados'
  ClientHeight = 433
  ClientWidth = 622
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  OnCreate = FormCreate
  TextHeight = 15
  object qryRelatorioEmpregados: TFDQuery
    Left = 64
    Top = 152
  end
  object dsRelatorioEmpregados: TDataSource
    DataSet = qryRelatorioEmpregados
    Left = 64
    Top = 96
  end
  object pprEmpregados: TppReport
    AutoStop = False
    DataPipeline = pplEmpregados
    PrinterSetup.BinName = 'Default'
    PrinterSetup.DocumentName = 'Report'
    PrinterSetup.PaperName = 'A4'
    PrinterSetup.PrinterName = 'Default'
    PrinterSetup.SaveDeviceSettings = False
    PrinterSetup.mmMarginBottom = 6350
    PrinterSetup.mmMarginLeft = 6350
    PrinterSetup.mmMarginRight = 6350
    PrinterSetup.mmMarginTop = 6350
    PrinterSetup.mmPaperHeight = 297000
    PrinterSetup.mmPaperWidth = 210000
    PrinterSetup.PaperSize = 9
    ArchiveFileName = '($MyDocuments)\ReportArchive.raf'
    DeviceType = 'Screen'
    DefaultFileDeviceType = 'PDF'
    EmailSettings.ReportFormat = 'PDF'
    EmailSettings.ConnectionSettings.MailService = 'SMTP'
    EmailSettings.ConnectionSettings.WebMail.GmailSettings.OAuth2.AuthStorage = [oasAccessToken, oasRefreshToken]
    EmailSettings.ConnectionSettings.WebMail.GmailSettings.OAuth2.RedirectURI = 'http://localhost'
    EmailSettings.ConnectionSettings.WebMail.GmailSettings.OAuth2.RedirectPort = 0
    EmailSettings.ConnectionSettings.WebMail.Outlook365Settings.OAuth2.AuthStorage = [oasAccessToken, oasRefreshToken]
    EmailSettings.ConnectionSettings.WebMail.Outlook365Settings.OAuth2.RedirectURI = 'http://localhost'
    EmailSettings.ConnectionSettings.WebMail.Outlook365Settings.OAuth2.RedirectPort = 0
    EmailSettings.ConnectionSettings.EnableMultiPlugin = False
    LanguageID = 'Default'
    OpenFile = False
    OutlineSettings.CreateNode = True
    OutlineSettings.CreatePageNodes = True
    OutlineSettings.Enabled = True
    OutlineSettings.Visible = True
    ThumbnailSettings.Enabled = True
    ThumbnailSettings.Visible = True
    ThumbnailSettings.DeadSpace = 30
    ThumbnailSettings.PageHighlight.Width = 3
    ThumbnailSettings.ThumbnailSize = tsSmall
    PDFSettings.EmbedFontOptions = [efUseSubset]
    PDFSettings.EncryptSettings.AllowCopy = True
    PDFSettings.EncryptSettings.AllowInteract = True
    PDFSettings.EncryptSettings.AllowModify = True
    PDFSettings.EncryptSettings.AllowPrint = True
    PDFSettings.EncryptSettings.AllowExtract = True
    PDFSettings.EncryptSettings.AllowAssemble = True
    PDFSettings.EncryptSettings.AllowQualityPrint = True
    PDFSettings.EncryptSettings.Enabled = False
    PDFSettings.EncryptSettings.KeyLength = kl40Bit
    PDFSettings.EncryptSettings.EncryptionType = etRC4
    PDFSettings.DigitalSignatureSettings.SignPDF = False
    PDFSettings.FontEncoding = feAnsi
    PDFSettings.ImageCompressionLevel = 25
    PDFSettings.PDFAFormat = pafNone
    PreviewFormSettings.PageBorder.mmPadding = 0
    RTFSettings.AppName = 'ReportBuilder'
    RTFSettings.Author = 'ReportBuilder'
    RTFSettings.DefaultFont.Charset = DEFAULT_CHARSET
    RTFSettings.DefaultFont.Color = clWindowText
    RTFSettings.DefaultFont.Height = -17
    RTFSettings.DefaultFont.Name = 'Arial'
    RTFSettings.DefaultFont.Style = []
    RTFSettings.Title = 'Report'
    TextFileName = '($MyDocuments)\Report.pdf'
    TextSearchSettings.DefaultString = '<FindText>'
    TextSearchSettings.Enabled = True
    XLSSettings.AppName = 'ReportBuilder'
    XLSSettings.Author = 'ReportBuilder'
    XLSSettings.Subject = 'Report'
    XLSSettings.Title = 'Report'
    XLSSettings.WorksheetName = 'Report'
    CloudDriveSettings.DropBoxSettings.OAuth2.AuthStorage = [oasAccessToken, oasRefreshToken]
    CloudDriveSettings.DropBoxSettings.OAuth2.RedirectURI = 'http://localhost'
    CloudDriveSettings.DropBoxSettings.OAuth2.RedirectPort = 0
    CloudDriveSettings.DropBoxSettings.DirectorySupport = True
    CloudDriveSettings.GoogleDriveSettings.OAuth2.AuthStorage = [oasAccessToken, oasRefreshToken]
    CloudDriveSettings.GoogleDriveSettings.OAuth2.RedirectURI = 'http://localhost'
    CloudDriveSettings.GoogleDriveSettings.OAuth2.RedirectPort = 0
    CloudDriveSettings.GoogleDriveSettings.DirectorySupport = False
    CloudDriveSettings.OneDriveSettings.OAuth2.AuthStorage = [oasAccessToken, oasRefreshToken]
    CloudDriveSettings.OneDriveSettings.OAuth2.RedirectURI = 'http://localhost'
    CloudDriveSettings.OneDriveSettings.OAuth2.RedirectPort = 0
    CloudDriveSettings.OneDriveSettings.DirectorySupport = True
    Left = 72
    Top = 240
    Version = '22.05'
    mmColumnWidth = 0
    DataPipelineName = 'pplEmpregados'
    object ppHeaderBand1: TppHeaderBand
      Border.mmPadding = 0
      mmBottomOffset = 0
      mmHeight = 17145
      mmPrintPosition = 0
      object plblTitulo: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'plblTitulo'
        Border.mmPadding = 0
        Caption = 'Relat'#243'rio de Empregados por Departamento'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Arial'
        Font.Size = 16
        Font.Style = []
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 6773
        mmLeft = 7620
        mmTop = 4025
        mmWidth = 113242
        BandType = 0
        LayerName = Foreground
      end
      object plblNome: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'plblNome'
        Border.mmPadding = 0
        Caption = 'Nome'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Arial'
        Font.Size = 10
        Font.Style = []
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 4022
        mmLeft = 7620
        mmTop = 13124
        mmWidth = 8890
        BandType = 0
        LayerName = Foreground
      end
      object plblFuncao: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'plblFuncao'
        Border.mmPadding = 0
        Caption = 'Fun'#231#227'o'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Arial'
        Font.Size = 10
        Font.Style = []
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 4022
        mmLeft = 45072
        mmTop = 13124
        mmWidth = 11642
        BandType = 0
        LayerName = Foreground
      end
      object plblDepartamento: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'plblDepartamento'
        Border.mmPadding = 0
        Caption = 'Departamento'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Arial'
        Font.Size = 10
        Font.Style = []
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 4022
        mmLeft = 74292
        mmTop = 13124
        mmWidth = 21590
        BandType = 0
        LayerName = Foreground
      end
      object plblLocal: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'plblLocal'
        Border.mmPadding = 0
        Caption = 'Local'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Arial'
        Font.Size = 10
        Font.Style = []
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 4022
        mmLeft = 102652
        mmTop = 13124
        mmWidth = 8255
        BandType = 0
        LayerName = Foreground
      end
      object plblAdmissao: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'plblAdmissao'
        Border.mmPadding = 0
        Caption = 'Admiss'#227'o'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Arial'
        Font.Size = 10
        Font.Style = []
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 4022
        mmLeft = 131244
        mmTop = 13124
        mmWidth = 15028
        BandType = 0
        LayerName = Foreground
      end
      object plblSalario: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'plblSalario'
        Border.mmPadding = 0
        Caption = 'Sal'#225'rio'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Arial'
        Font.Size = 10
        Font.Style = []
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 4022
        mmLeft = 151988
        mmTop = 13124
        mmWidth = 10795
        BandType = 0
        LayerName = Foreground
      end
      object plblComissao: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'plblComissao'
        Border.mmPadding = 0
        Caption = 'Comiss'#227'o'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Arial'
        Font.Size = 10
        Font.Style = []
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 4022
        mmLeft = 175700
        mmTop = 13124
        mmWidth = 15240
        BandType = 0
        LayerName = Foreground
      end
      object ppLine1: TppLine
        DesignLayer = ppDesignLayer1
        UserName = 'Line1'
        Border.mmPadding = 0
        Position = lpBottom
        Weight = 0.600000023841857900
        mmHeight = 2117
        mmLeft = 5712
        mmTop = 15028
        mmWidth = 185844
        BandType = 0
        LayerName = Foreground
      end
    end
    object ppDetailBand1: TppDetailBand
      Border.mmPadding = 0
      mmBottomOffset = 0
      mmHeight = 4022
      mmPrintPosition = 0
      object dlblNome: TppDBText
        DesignLayer = ppDesignLayer1
        UserName = 'dlblNome'
        Border.mmPadding = 0
        DataField = 'nm_empregado'
        DataPipeline = pplEmpregados
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Arial'
        Font.Size = 9
        Font.Style = []
        Transparent = True
        DataPipelineName = 'pplEmpregados'
        mmHeight = 3598
        mmLeft = 7620
        mmTop = 0
        mmWidth = 36195
        BandType = 4
        LayerName = Foreground
      end
      object dlblFuncao: TppDBText
        DesignLayer = ppDesignLayer1
        UserName = 'dlblFuncao'
        Border.mmPadding = 0
        DataField = 'nm_funcao'
        DataPipeline = pplEmpregados
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Arial'
        Font.Size = 9
        Font.Style = []
        Transparent = True
        DataPipelineName = 'pplEmpregados'
        mmHeight = 3598
        mmLeft = 45072
        mmTop = 0
        mmWidth = 27728
        BandType = 4
        LayerName = Foreground
      end
      object dlblDepartamento: TppDBText
        DesignLayer = ppDesignLayer1
        UserName = 'dlblDepartamento'
        Border.mmPadding = 0
        DataField = 'nm_departamento'
        DataPipeline = pplEmpregados
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Arial'
        Font.Size = 9
        Font.Style = []
        Transparent = True
        DataPipelineName = 'pplEmpregados'
        mmHeight = 3598
        mmLeft = 74292
        mmTop = 0
        mmWidth = 27305
        BandType = 4
        LayerName = Foreground
      end
      object dlblLocal: TppDBText
        DesignLayer = ppDesignLayer1
        UserName = 'dlblLocal'
        Border.mmPadding = 0
        DataField = 'local'
        DataPipeline = pplEmpregados
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Arial'
        Font.Size = 9
        Font.Style = []
        Transparent = True
        DataPipelineName = 'pplEmpregados'
        mmHeight = 3598
        mmLeft = 102652
        mmTop = 0
        mmWidth = 26882
        BandType = 4
        LayerName = Foreground
      end
      object dlblAdmissao: TppDBText
        DesignLayer = ppDesignLayer1
        UserName = 'dlblAdmissao'
        Border.mmPadding = 0
        DataField = 'data_admissao'
        DataPipeline = pplEmpregados
        DisplayFormat = 'dd/mm/yyyy'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Arial'
        Font.Size = 9
        Font.Style = []
        Transparent = True
        DataPipelineName = 'pplEmpregados'
        mmHeight = 3598
        mmLeft = 131244
        mmTop = 0
        mmWidth = 18627
        BandType = 4
        LayerName = Foreground
      end
      object dlblSalario: TppDBText
        DesignLayer = ppDesignLayer1
        UserName = 'dlblSalario'
        Border.mmPadding = 0
        DataField = 'salario'
        DataPipeline = pplEmpregados
        DisplayFormat = '#,##0.00'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Arial'
        Font.Size = 9
        Font.Style = []
        Transparent = True
        DataPipelineName = 'pplEmpregados'
        mmHeight = 3598
        mmLeft = 151988
        mmTop = 0
        mmWidth = 22013
        BandType = 4
        LayerName = Foreground
      end
      object dlblComissao: TppDBText
        DesignLayer = ppDesignLayer1
        UserName = 'dlblComissao'
        Border.mmPadding = 0
        DataField = 'comissao'
        DataPipeline = pplEmpregados
        DisplayFormat = '#,##0.00'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Arial'
        Font.Size = 9
        Font.Style = []
        Transparent = True
        DataPipelineName = 'pplEmpregados'
        mmHeight = 3598
        mmLeft = 175700
        mmTop = 0
        mmWidth = 15240
        BandType = 4
        LayerName = Foreground
      end
    end
    object ppFooterBand1: TppFooterBand
      Border.mmPadding = 0
      mmBottomOffset = 0
      mmHeight = 4445
      mmPrintPosition = 0
      object ppDBCalc1: TppDBCalc
        DesignLayer = ppDesignLayer1
        UserName = 'DBCalc1'
        Border.mmPadding = 0
        DataField = 'salario'
        DataPipeline = pplEmpregados
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Arial'
        Font.Size = 10
        Font.Style = []
        Transparent = True
        DataPipelineName = 'pplEmpregados'
        mmHeight = 4022
        mmLeft = 131657
        mmTop = 423
        mmWidth = 32385
        BandType = 8
        LayerName = Foreground
      end
      object plblTotal: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'plblTotal'
        Border.mmPadding = 0
        Caption = 'Total'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Arial'
        Font.Size = 10
        Font.Style = []
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 4022
        mmLeft = 7620
        mmTop = 423
        mmWidth = 7197
        BandType = 8
        LayerName = Foreground
      end
    end
    object ppDesignLayers1: TppDesignLayers
      object ppDesignLayer1: TppDesignLayer
        UserName = 'Foreground'
        LayerType = ltBanded
        Index = 0
      end
    end
    object ppParameterList1: TppParameterList
    end
  end
  object pplEmpregados: TppDBPipeline
    DataSource = dsRelatorioEmpregados
    UserName = 'lEmpregados'
    Left = 48
    Top = 312
  end
end
